import { Run } from "./types";

export const runs: Run[] = [
  // ─── Production Daily Run (job-1) ──────────────────────────────────────────
  {
    id: "run-1",
    jobId: "job-1",
    jobName: "Production Daily Run",
    status: "success",
    startedAt: "2025-01-27T06:00:12Z",
    finishedAt: "2025-01-27T06:04:47Z",
    duration: 275,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 8,
        logs: `Cloning into '/tmp/dbt-run-1/jaffle-shop'...\nremote: Enumerating objects: 342, done.\nremote: Counting objects: 100% (342/342), done.\nremote: Compressing objects: 100% (198/198), done.\nHEAD is now at a3c7f2e feat: add metricstore_daily_revenue model`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 12,
        logs: `Installing dbt-core==1.7.4 dbt-bigquery==1.7.4\nSuccessfully installed dbt-core-1.7.4 dbt-bigquery-1.7.4\nRunning with dbt=1.7.4\nRegistered adapter: bigquery=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "success",
        duration: 15,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\n06:00:32  1 of 4 START freshness of jaffle_shop.orders .............. [RUN]\n06:00:33  1 of 4 OK freshness of jaffle_shop.orders ................. [PASS in 1.24s]\n06:00:33  2 of 4 START freshness of jaffle_shop.customers ........... [RUN]\n06:00:34  2 of 4 OK freshness of jaffle_shop.customers .............. [PASS in 0.98s]\n06:00:34  3 of 4 START freshness of stripe.payments ................. [RUN]\n06:00:35  3 of 4 OK freshness of stripe.payments .................... [PASS in 1.11s]\n06:00:35  4 of 4 START freshness of jaffle_shop.products ............ [RUN]\n06:00:36  4 of 4 OK freshness of jaffle_shop.products ............... [PASS in 0.87s]\n\nDone. PASS=4 WARN=0 ERROR=0 TOTAL=4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 218,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\nConcurrency: 4 threads (target='prod')\n\n06:00:52  1 of 15 START sql view model staging.stg_orders .............. [RUN]\n06:00:52  2 of 15 START sql view model staging.stg_customers ........... [RUN]\n06:00:52  3 of 15 START sql view model staging.stg_payments ............ [RUN]\n06:00:52  4 of 15 START sql view model staging.stg_products ............ [RUN]\n06:00:54  1 of 15 OK created sql view model staging.stg_orders ......... [CREATE VIEW in 1.85s]\n06:00:54  2 of 15 OK created sql view model staging.stg_customers ...... [CREATE VIEW in 1.92s]\n06:00:55  3 of 15 OK created sql view model staging.stg_payments ....... [CREATE VIEW in 2.10s]\n06:00:55  4 of 15 OK created sql view model staging.stg_products ....... [CREATE VIEW in 2.04s]\n06:00:55  5 of 15 START sql table model marts.dim_customers ............ [RUN]\n06:00:55  6 of 15 START sql table model marts.dim_products ............. [RUN]\n06:00:58  5 of 15 OK created sql table model marts.dim_customers ....... [CREATE TABLE in 3.41s]\n06:00:59  6 of 15 OK created sql table model marts.dim_products ........ [CREATE TABLE in 3.22s]\n06:00:59  7 of 15 START sql incremental model marts.fct_orders ......... [RUN]\n06:00:59  8 of 15 START sql incremental model marts.fct_revenue ........ [RUN]\n06:01:04  7 of 15 OK created sql incremental model marts.fct_orders .... [MERGE in 5.12s]\n06:01:05  8 of 15 OK created sql incremental model marts.fct_revenue ... [MERGE in 5.43s]\n06:01:05  9 of 15 START sql table model metrics.metricstore_daily_revenue [RUN]\n06:01:10  9 of 15 OK created sql table model metrics.metricstore_daily_revenue [CREATE TABLE in 4.87s]\n06:01:10  Running 38 tests...\n06:01:22  37 of 38 tests PASSED\n06:01:22  1 of 38 tests FAILED — fct_orders_total_amount_positive\n\nFinished running 15 models, 38 tests in 218.42s.\n\nCompleted successfully.\n\nDone. PASS=52 WARN=0 ERROR=0 SKIP=0 TOTAL=52`,
      },
      {
        name: "Upload Artifacts",
        status: "success",
        duration: 6,
        logs: `Uploading manifest.json (342 KB)...\nUploading run_results.json (128 KB)...\nUploading catalog.json (87 KB)...\nArtifacts uploaded successfully.`,
      },
    ],
  },
  {
    id: "run-2",
    jobId: "job-1",
    jobName: "Production Daily Run",
    status: "success",
    startedAt: "2025-01-26T06:00:08Z",
    finishedAt: "2025-01-26T06:04:31Z",
    duration: 263,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 7,
        logs: `Cloning into '/tmp/dbt-run-2/jaffle-shop'...\nHEAD is now at b1d9e4a chore: update schema tests`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 11,
        logs: `Installing dbt-core==1.7.4 dbt-bigquery==1.7.4\nSuccessfully installed dbt-core-1.7.4\nRunning with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "success",
        duration: 14,
        logs: `Running with dbt=1.7.4\nDone. PASS=4 WARN=0 ERROR=0 TOTAL=4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 225,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\nConcurrency: 4 threads (target='prod')\n\nFinished running 15 models, 38 tests in 225.11s.\n\nCompleted successfully.\n\nDone. PASS=53 WARN=0 ERROR=0 SKIP=0 TOTAL=53`,
      },
      {
        name: "Upload Artifacts",
        status: "success",
        duration: 6,
        logs: `Uploading manifest.json (342 KB)...\nArtifacts uploaded successfully.`,
      },
    ],
  },
  {
    id: "run-3",
    jobId: "job-1",
    jobName: "Production Daily Run",
    status: "success",
    startedAt: "2025-01-25T06:00:05Z",
    finishedAt: "2025-01-25T06:04:18Z",
    duration: 253,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-3/jaffle-shop'...\nHEAD is now at e8f2a11 fix: correct stg_payments amount cast`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 10,
        logs: `Installing dbt-core==1.7.4\nRunning with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "success",
        duration: 13,
        logs: `Done. PASS=4 WARN=0 ERROR=0 TOTAL=4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 219,
        logs: `Running with dbt=1.7.4\nFinished running 15 models, 38 tests in 219.33s.\nDone. PASS=53 WARN=0 ERROR=0 SKIP=0 TOTAL=53`,
      },
      {
        name: "Upload Artifacts",
        status: "success",
        duration: 5,
        logs: `Artifacts uploaded successfully.`,
      },
    ],
  },
  {
    id: "run-4",
    jobId: "job-1",
    jobName: "Production Daily Run",
    status: "error",
    startedAt: "2025-01-24T06:00:11Z",
    finishedAt: "2025-01-24T06:02:34Z",
    duration: 143,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 7,
        logs: `Cloning into '/tmp/dbt-run-4/jaffle-shop'...\nHEAD is now at 5c2d891 feat: add accepted_values test to stg_orders`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 11,
        logs: `Installing dbt-core==1.7.4\nRunning with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "error",
        duration: 42,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\n06:00:29  1 of 4 START freshness of jaffle_shop.orders .............. [RUN]\n06:00:30  1 of 4 OK freshness of jaffle_shop.orders ................. [PASS in 1.10s]\n06:00:30  2 of 4 START freshness of jaffle_shop.customers ........... [RUN]\n06:00:31  2 of 4 OK freshness of jaffle_shop.customers .............. [PASS in 1.03s]\n06:00:31  3 of 4 START freshness of stripe.payments ................. [RUN]\n06:00:52  3 of 4 ERROR freshness of stripe.payments .................. [ERROR in 21.42s]\nRuntime Error\n  Database Error in source freshness stripe.payments\n  404 Not Found: Table stripe.payments was not found in location US\n\nDone. PASS=2 WARN=0 ERROR=1 TOTAL=4\nENCOUNTERED AN ERROR`,
      },
      {
        name: "Invoke dbt build",
        status: "skipped",
        duration: 0,
        logs: `Skipped due to previous step failure.`,
      },
      {
        name: "Upload Artifacts",
        status: "skipped",
        duration: 0,
        logs: `Skipped due to previous step failure.`,
      },
    ],
  },

  // ─── Production Hourly Incremental (job-2) ─────────────────────────────────
  {
    id: "run-5",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "error",
    startedAt: "2025-01-27T14:00:03Z",
    finishedAt: "2025-01-27T14:01:47Z",
    duration: 104,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-5/jaffle-shop'...\nHEAD is now at a3c7f2e feat: add metricstore_daily_revenue model`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 10,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "error",
        duration: 85,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\nConcurrency: 4 threads (target='prod')\n\n14:00:19  1 of 2 START sql incremental model marts.fct_orders ......... [RUN]\n14:00:19  2 of 2 START sql incremental model marts.fct_revenue ........ [RUN]\n14:00:34  1 of 2 ERROR creating sql incremental model marts.fct_orders  [ERROR in 14.98s]\nDatabase Error in model fct_orders (models/marts/fct_orders.sql)\n  Quota exceeded: Your project exceeded quota for concurrent queries.\n  Project: prod-project\n14:00:35  2 of 2 OK created sql incremental model marts.fct_revenue ... [MERGE in 15.21s]\n\nFinished running 2 models in 85.33s.\n\nCompleted with 1 error:\n\n  Database Error in model fct_orders\n    Quota exceeded: concurrent queries\n\nDone. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2`,
      },
    ],
  },
  {
    id: "run-6",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "success",
    startedAt: "2025-01-27T13:00:04Z",
    finishedAt: "2025-01-27T13:01:22Z",
    duration: 78,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-6/jaffle-shop'...\nHEAD is now at a3c7f2e feat: add metricstore_daily_revenue model`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 9,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 63,
        logs: `Running with dbt=1.7.4\n\n13:00:19  1 of 2 START sql incremental model marts.fct_orders ......... [RUN]\n13:00:19  2 of 2 START sql incremental model marts.fct_revenue ........ [RUN]\n13:00:28  1 of 2 OK created sql incremental model marts.fct_orders .... [MERGE in 9.12s]\n13:00:29  2 of 2 OK created sql incremental model marts.fct_revenue ... [MERGE in 9.44s]\n\nDone. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2`,
      },
    ],
  },
  {
    id: "run-7",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "success",
    startedAt: "2025-01-27T12:00:02Z",
    finishedAt: "2025-01-27T12:01:18Z",
    duration: 76,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 5,
        logs: `Cloning into '/tmp/dbt-run-7/jaffle-shop'...\nHEAD is now at a3c7f2e feat: add metricstore_daily_revenue model`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 10,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 61,
        logs: `Running with dbt=1.7.4\n\n12:00:17  1 of 2 START sql incremental model marts.fct_orders ......... [RUN]\n12:00:17  2 of 2 START sql incremental model marts.fct_revenue ........ [RUN]\n12:00:25  1 of 2 OK created sql incremental model marts.fct_orders .... [MERGE in 8.34s]\n12:00:26  2 of 2 OK created sql incremental model marts.fct_revenue ... [MERGE in 8.81s]\n\nDone. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2`,
      },
    ],
  },
  {
    id: "run-8",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "success",
    startedAt: "2025-01-27T11:00:05Z",
    finishedAt: "2025-01-27T11:01:21Z",
    duration: 76,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-8/jaffle-shop'...\nHEAD is now at a3c7f2e feat: add metricstore_daily_revenue model`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 9,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 61,
        logs: `Running with dbt=1.7.4\n\nDone. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2`,
      },
    ],
  },
  {
    id: "run-9",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "success",
    startedAt: "2025-01-27T10:00:04Z",
    finishedAt: "2025-01-27T10:01:14Z",
    duration: 70,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 5,
        logs: `Cloning into '/tmp/dbt-run-9/jaffle-shop'...\nHEAD is now at a3c7f2e`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 9,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 56,
        logs: `Running with dbt=1.7.4\n\nDone. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2`,
      },
    ],
  },
  {
    id: "run-10",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "error",
    startedAt: "2025-01-26T18:00:03Z",
    finishedAt: "2025-01-26T18:02:01Z",
    duration: 118,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-10/jaffle-shop'...\nHEAD is now at b1d9e4a chore: update schema tests`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 10,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "error",
        duration: 102,
        logs: `Running with dbt=1.7.4\n\n18:00:19  1 of 2 START sql incremental model marts.fct_orders ......... [RUN]\n18:00:19  2 of 2 START sql incremental model marts.fct_revenue ........ [RUN]\n18:01:19  1 of 2 ERROR creating sql incremental model marts.fct_orders  [ERROR in 60.22s]\nDatabase Error in model fct_orders (models/marts/fct_orders.sql)\n  Timeout: Query timed out after 60 seconds.\n18:01:41  2 of 2 OK created sql incremental model marts.fct_revenue ... [MERGE in 82.14s]\n\nDone. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2`,
      },
    ],
  },
  {
    id: "run-11",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "success",
    startedAt: "2025-01-26T17:00:02Z",
    finishedAt: "2025-01-26T17:01:10Z",
    duration: 68,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 5,
        logs: `Cloning into '/tmp/dbt-run-11/jaffle-shop'...\nHEAD is now at b1d9e4a`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 9,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 54,
        logs: `Running with dbt=1.7.4\n\nDone. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2`,
      },
    ],
  },

  // ─── Staging Full Refresh (job-3) ──────────────────────────────────────────
  {
    id: "run-12",
    jobId: "job-3",
    jobName: "Staging Full Refresh",
    status: "success",
    startedAt: "2025-01-27T04:00:06Z",
    finishedAt: "2025-01-27T04:08:42Z",
    duration: 516,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 7,
        logs: `Cloning into '/tmp/dbt-run-12/jaffle-shop'...\nremote: Enumerating objects: 342, done.\nHEAD is now at a3c7f2e feat: add metricstore_daily_revenue model`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 12,
        logs: `Installing dbt-core==1.7.4 dbt-bigquery==1.7.4\nRunning with dbt=1.7.4\nRegistered adapter: bigquery=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "success",
        duration: 16,
        logs: `Running with dbt=1.7.4\nDone. PASS=4 WARN=0 ERROR=0 TOTAL=4`,
      },
      {
        name: "Invoke dbt build --full-refresh",
        status: "success",
        duration: 462,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\nConcurrency: 4 threads (target='staging')\n\n04:00:41  1 of 15 START sql view model staging.stg_orders .............. [RUN]\n04:00:41  2 of 15 START sql view model staging.stg_customers ........... [RUN]\n04:00:41  3 of 15 START sql view model staging.stg_payments ............ [RUN]\n04:00:41  4 of 15 START sql view model staging.stg_products ............ [RUN]\n04:00:43  1 of 15 OK created sql view model staging.stg_orders ......... [CREATE VIEW in 2.11s]\n04:00:43  2 of 15 OK created sql view model staging.stg_customers ...... [CREATE VIEW in 2.24s]\n04:00:44  3 of 15 OK created sql view model staging.stg_payments ....... [CREATE VIEW in 2.37s]\n04:00:44  4 of 15 OK created sql view model staging.stg_products ....... [CREATE VIEW in 2.18s]\n04:00:44  5 of 15 START sql table model marts.dim_customers ............ [RUN]\n04:00:44  6 of 15 START sql table model marts.dim_products ............. [RUN]\n04:00:49  5 of 15 OK created sql table model marts.dim_customers ....... [CREATE TABLE in 4.82s]\n04:00:49  6 of 15 OK created sql table model marts.dim_products ........ [CREATE TABLE in 4.56s]\n04:00:49  7 of 15 START sql table model marts.fct_orders (full-refresh)  [RUN]\n04:00:49  8 of 15 START sql table model marts.fct_revenue (full-refresh) [RUN]\n04:01:02  7 of 15 OK created sql table model marts.fct_orders .......... [CREATE TABLE in 12.88s]\n04:01:03  8 of 15 OK created sql table model marts.fct_revenue ......... [CREATE TABLE in 13.22s]\n04:01:03  9 of 15 START sql table model metrics.metricstore_daily_revenue [RUN]\n04:01:11  9 of 15 OK created sql table model metrics.metricstore_daily_revenue [CREATE TABLE in 8.14s]\n04:01:11  Running 38 tests...\n04:07:43  38 of 38 tests PASSED\n\nFinished running 15 models, 38 tests in 462.18s.\n\nDone. PASS=53 WARN=0 ERROR=0 SKIP=0 TOTAL=53`,
      },
      {
        name: "Upload Artifacts",
        status: "success",
        duration: 7,
        logs: `Uploading manifest.json (342 KB)...\nUploading run_results.json (128 KB)...\nArtifacts uploaded successfully.`,
      },
    ],
  },
  {
    id: "run-13",
    jobId: "job-3",
    jobName: "Staging Full Refresh",
    status: "success",
    startedAt: "2025-01-20T04:00:09Z",
    finishedAt: "2025-01-20T04:08:21Z",
    duration: 492,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 8,
        logs: `Cloning into '/tmp/dbt-run-13/jaffle-shop'...\nHEAD is now at 2f1a98c feat: add dim_products model`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 11,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "success",
        duration: 15,
        logs: `Done. PASS=4 WARN=0 ERROR=0 TOTAL=4`,
      },
      {
        name: "Invoke dbt build --full-refresh",
        status: "success",
        duration: 451,
        logs: `Running with dbt=1.7.4\nFound 14 models, 4 sources, 36 tests, 0 snapshots\n\nFinished running 14 models, 36 tests in 451.22s.\n\nDone. PASS=50 WARN=0 ERROR=0 SKIP=0 TOTAL=50`,
      },
      {
        name: "Upload Artifacts",
        status: "success",
        duration: 7,
        logs: `Artifacts uploaded successfully.`,
      },
    ],
  },

  // ─── Slim CI (job-5) ───────────────────────────────────────────────────────
  {
    id: "run-14",
    jobId: "job-5",
    jobName: "Slim CI",
    status: "success",
    startedAt: "2025-01-27T15:22:44Z",
    finishedAt: "2025-01-27T15:23:31Z",
    duration: 47,
    trigger: "git",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-14/jaffle-shop'...\nChecking out PR #142: feat/add-product-category-filter\nHEAD is now at f7e3b21 feat: filter products by category`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 10,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build --select state:modified+",
        status: "success",
        duration: 28,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\n15:23:00  Comparing local state to remote state (prod-manifest)...\n15:23:01  Found 2 modified models: stg_products, dim_products\n15:23:01  1 of 2 START sql view model staging.stg_products ............ [RUN]\n15:23:03  1 of 2 OK created sql view model staging.stg_products ....... [CREATE VIEW in 1.88s]\n15:23:03  2 of 2 START sql table model marts.dim_products ............. [RUN]\n15:23:07  2 of 2 OK created sql table model marts.dim_products ........ [CREATE TABLE in 3.54s]\n15:23:07  Running 8 tests on modified models...\n15:23:14  8 of 8 tests PASSED\n\nDone. PASS=10 WARN=0 ERROR=0 SKIP=0 TOTAL=10`,
      },
    ],
  },
  {
    id: "run-15",
    jobId: "job-5",
    jobName: "Slim CI",
    status: "success",
    startedAt: "2025-01-27T11:45:12Z",
    finishedAt: "2025-01-27T11:45:54Z",
    duration: 42,
    trigger: "git",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 5,
        logs: `Cloning into '/tmp/dbt-run-15/jaffle-shop'...\nChecking out PR #141: fix/payment-amount-rounding\nHEAD is now at c4a2d88 fix: round payment amounts to 2 decimal places`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 9,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build --select state:modified+",
        status: "success",
        duration: 25,
        logs: `Running with dbt=1.7.4\n\n11:45:26  Comparing local state to remote state (prod-manifest)...\n11:45:27  Found 1 modified model: stg_payments\n11:45:27  1 of 1 START sql view model staging.stg_payments ............ [RUN]\n11:45:29  1 of 1 OK created sql view model staging.stg_payments ....... [CREATE VIEW in 1.72s]\n11:45:29  Running 4 tests on modified models...\n11:45:34  4 of 4 tests PASSED\n\nDone. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5`,
      },
    ],
  },
  {
    id: "run-16",
    jobId: "job-5",
    jobName: "Slim CI",
    status: "error",
    startedAt: "2025-01-26T16:33:08Z",
    finishedAt: "2025-01-26T16:33:52Z",
    duration: 44,
    trigger: "git",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-16/jaffle-shop'...\nChecking out PR #140: feat/add-customer-lifetime-value\nHEAD is now at 9b1e7fd feat: add customer_lifetime_value to dim_customers`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 10,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build --select state:modified+",
        status: "error",
        duration: 28,
        logs: `Running with dbt=1.7.4\n\n16:33:24  Comparing local state to remote state (prod-manifest)...\n16:33:25  Found 2 modified models: int_customer_orders, dim_customers\n16:33:25  1 of 2 START sql table model marts.dim_customers ............ [RUN]\n16:33:31  1 of 2 ERROR creating sql table model marts.dim_customers .... [ERROR in 5.88s]\nCompilation Error in model dim_customers (models/marts/dim_customers.sql)\n  'customer_lifetime_value' is undefined. This can happen when:\n  - The column is not in the upstream model\n  - There is a typo in the column name\n\n16:33:31  2 of 2 SKIP sql table model marts.dim_customers\n\nDone. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2`,
      },
    ],
  },
  {
    id: "run-17",
    jobId: "job-5",
    jobName: "Slim CI",
    status: "success",
    startedAt: "2025-01-25T09:18:33Z",
    finishedAt: "2025-01-25T09:19:12Z",
    duration: 39,
    trigger: "git",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 5,
        logs: `Cloning into '/tmp/dbt-run-17/jaffle-shop'...\nChecking out PR #139: docs/update-model-descriptions\nHEAD is now at 8d4f1a2 docs: update model descriptions in schema.yml`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 9,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build --select state:modified+",
        status: "success",
        duration: 22,
        logs: `Running with dbt=1.7.4\n\n09:18:47  Comparing local state to remote state (prod-manifest)...\n09:18:48  No modified models detected. Nothing to build.\n\nDone. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0`,
      },
    ],
  },

  // ─── Manual / ad-hoc runs ──────────────────────────────────────────────────
  {
    id: "run-18",
    jobId: "job-1",
    jobName: "Production Daily Run",
    status: "success",
    startedAt: "2025-01-23T19:45:22Z",
    finishedAt: "2025-01-23T19:49:58Z",
    duration: 276,
    trigger: "manual",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 7,
        logs: `Cloning into '/tmp/dbt-run-18/jaffle-shop'...\nHEAD is now at 5c2d891 feat: add accepted_values test to stg_orders`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 11,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "success",
        duration: 14,
        logs: `Done. PASS=4 WARN=0 ERROR=0 TOTAL=4`,
      },
      {
        name: "Invoke dbt build",
        status: "success",
        duration: 238,
        logs: `Running with dbt=1.7.4\nFound 15 models, 4 sources, 38 tests, 0 snapshots\n\nFinished running 15 models, 38 tests in 238.14s.\n\nDone. PASS=53 WARN=0 ERROR=0 SKIP=0 TOTAL=53`,
      },
      {
        name: "Upload Artifacts",
        status: "success",
        duration: 6,
        logs: `Artifacts uploaded successfully.`,
      },
    ],
  },
  {
    id: "run-19",
    jobId: "job-2",
    jobName: "Production Hourly Incremental",
    status: "cancelled",
    startedAt: "2025-01-25T22:00:04Z",
    finishedAt: "2025-01-25T22:00:38Z",
    duration: 34,
    trigger: "scheduled",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 6,
        logs: `Cloning into '/tmp/dbt-run-19/jaffle-shop'...\nHEAD is now at e8f2a11 fix: correct stg_payments amount cast`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 10,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt build",
        status: "skipped",
        duration: 0,
        logs: `Run cancelled by user (ben.moser@dbt-labs.com) at 22:00:38 UTC.\nReason: Maintenance window — pausing hourly runs.`,
      },
    ],
  },
  {
    id: "run-20",
    jobId: "job-3",
    jobName: "Staging Full Refresh",
    status: "success",
    startedAt: "2025-01-22T14:12:55Z",
    finishedAt: "2025-01-22T14:20:48Z",
    duration: 473,
    trigger: "manual",
    steps: [
      {
        name: "Clone Git Repository",
        status: "success",
        duration: 7,
        logs: `Cloning into '/tmp/dbt-run-20/jaffle-shop'...\nHEAD is now at 1a9c4b2 fix: update int_customer_orders join condition`,
      },
      {
        name: "Create dbt Environment",
        status: "success",
        duration: 12,
        logs: `Running with dbt=1.7.4`,
      },
      {
        name: "Invoke dbt source freshness",
        status: "success",
        duration: 15,
        logs: `Done. PASS=4 WARN=0 ERROR=0 TOTAL=4`,
      },
      {
        name: "Invoke dbt build --full-refresh",
        status: "success",
        duration: 432,
        logs: `Running with dbt=1.7.4\nFound 14 models, 4 sources, 35 tests, 0 snapshots\n\nFinished running 14 models, 35 tests in 432.44s.\n\nDone. PASS=49 WARN=0 ERROR=0 SKIP=0 TOTAL=49`,
      },
      {
        name: "Upload Artifacts",
        status: "success",
        duration: 7,
        logs: `Artifacts uploaded successfully.`,
      },
    ],
  },
];
